### ISSUE TITLE
Only reports for the second native image are generated

### ISSUE THREAD

**Issue by mio-19** [graalvm/setup-graalvm#104]
I build two native images in github actions. I enabled `native-image-job-reports` but I can only see reports of the second native image

**Comment by fniephaus** [comment]
Hi @mio-19,

This is a known limitation of the feature:

> *) Make sure that Native Image is used only once per build job. Otherwise, the report is only generated for the last Native Image build.

See at the end of the [Options](https://github.com/graalvm/setup-graalvm?tab=readme-ov-file#options).


To work around this, you could build the two native images in two different [build jobs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-jobs-in-a-workflow).

Hope this helps!
