### ISSUE TITLE
Cannot create musl based native image

### ISSUE THREAD

**Issue by edigonzales** [graalvm/setup-graalvm#12]
There seems to be a problem installing some stuff needed for building a musl based native image. I get timeouts when the action tries to setup musl: 

```

Setting up musl for GraalVM Native Image...
  connect ETIMEDOUT 104.232.42.245:80
  Waiting 11 seconds before trying again
  connect ETIMEDOUT 104.232.42.245:80
  Waiting 17 seconds before trying again
  Error: connect ETIMEDOUT 104.232.42.245:80
```

A quick look into the code makes me think that this is the problem: https://github.com/graalvm/setup-graalvm/blob/main/src/features.ts#L20

It tries to download something from http://more.musl.cc (104.232.42.245) which cannot be resolved.

**Comment by edigonzales** [comment]
It did not work on July 30, 17:16 CEST. Then I changed to non-musl in one repo. While working on another repo on August 2, 16:31 CEST _it did work_. Few minutes later it was broken.

**Comment by edigonzales** [comment]
I added a github action scheduler to one repo to see if it's conditional on the time of day.

**Comment by edigonzales** [comment]
Sometimes it works, sometimes it does not:

![Screenshot 2022-08-03 at 16 36 20](https://user-images.githubusercontent.com/2767800/182635738-9520ada4-1b5d-4b1a-b2f5-ddcf26a69ae2.png)

**Comment by fniephaus** [comment]
Thanks for checking! Looks like we'll have to do something about this. Will look into mirroring the external dependency somehow.

**Comment by fniephaus** [comment]
Could you please monitor your builds for a few more hours and check whether this problem has now been resolved? If not, please re-open this issue.

**Comment by edigonzales** [comment]
All green for the last 12h. Thanks.

**Comment by fniephaus** [comment]
Thanks for checking!
