### ISSUE TITLE
Github action 22.3.0 does not work on Linux anymore

### ISSUE THREAD

**Issue by strokyl** [graalvm/setup-graalvm#15]
When using:
```
     - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'js'
```

We got:

```
Run graalvm/setup-graalvm@v1
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/2001f429-3c1a-4eab-a464-d104551b4859 -f /home/runner/work/_temp/9b690481-8975-4f3b-90af-030c430177c1
Adding graalvm-ce-java17-linux 22.3.0 to tool-cache ...
/opt/hostedtoolcache/graalvm-ce-java17-linux/22.3.0/x64/graalvm-ce-java17-22.3.0/bin/gu --non-interactive install --no-progress js
Downloading: Component catalog from www.graalvm.org
Could not load channel https://www.graalvm.org/component-catalog/v2/graal-updater-component-catalog-java17.properties: Unsupported GraalVM version: 22.3.0, platform linux/amd64
Error: Unsupported GraalVM version: 22.3.0, platform linux/amd64
Error: The process '/opt/hostedtoolcache/graalvm-ce-java17-linux/22.3.0/x64/graalvm-ce-java17-22.3.0/bin/gu' failed with exit code 3``
```

**Comment by fniephaus** [comment]
We've just rolled out the 22.3 release and your build ran during the small window whether some of our bits were inconsistent. This should now work again. I'm going to follow up with our infra team to find a way how we can roll this out without breaking builds in the future.

**Comment by mdubey-tw** [comment]
Hello Everyone

Today we have started getting the similar issue for version `23.0.3`. We were seeing sometime back as below:

```
Error: Unsupported GraalVM version: 23.0.3, platform linux/amd64
```

Although in the latest runs the version part is gone in the error:
```
Error: Unsupported GraalVM release: OS: linux, arch: amd64, java version: 17
```

**Comment by fniephaus** [comment]
Hey @mdubey-tw, thanks for reporting! We are rolling out new patch releases and there are unfortunately some technical issues that we are currently working on. Apologies for the inconvenience this is causing. I expect this to be resolve in a couple of hours.

**Comment by mdubey-tw** [comment]
Sure @fniephaus!
Thank you for your quick response!
