### ISSUE TITLE
Deprecation of save-state 

### ISSUE THREAD

**Issue by grevend** [graalvm/setup-graalvm#16]
Dear GraalVM Team,

During my upgrade process to version `22.3.0`, it has come to my attention that GitHub issues the following warning when using this action:

> Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information, see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

This issue has seemingly been resolved in version `1.10.0` of `@actions/core`, as can be seen in https://github.com/actions/toolkit/pull/1178 and subsequent pull requests in projects like setup-java (https://github.com/actions/setup-java/pull/390). 

Are there currently any plans to resolve this future (31st May 2023) problem?

Thanks in advance!

**Comment by fniephaus** [comment]
Thanks for reporting this. We'll look into a fix tomorrow.
