### ISSUE TITLE
[FR] Add support for Mandrel trunk builds

### ISSUE THREAD

**Issue by zakkak** [graalvm/setup-graalvm#2]
#1 adds support for Mandrel releases. This issue is to track the addition of support for Mandrel `trunk` builds.

Please assign this issue to me.

**Comment by fniephaus** [comment]
Thanks for looking into this, @zakkak. Before we start: what use cases do we have for providing the ability to build Mandrel from source? Is this essentially compensating the lack of Mandel nightly (or dev) builds?

**Comment by zakkak** [comment]
> Is this essentially compensating the lack of Mandel nightly (or dev) builds?

Yes, I think that would be the main use case. 

Note that Mandrel's trunk is essentially the oracle/graal `head`, as a result `mandrel-trunk` and `trunk` would build the same source code, just with a different "configuration".

**Comment by zakkak** [comment]
Closing this as `trunk` has now been deprecated (see #3 ) and, although Mandrel can be built on reasonable time on github actions, adding a `mandrel-trunk` without `trunk` wouldn't be consistent or of much use (i.e. one couldn't test both distributions in a test matrix). People interested in building Mandrel from source in their github workflows are advised to have a look at https://github.com/graalvm/mandrel/blob/9c69df0897174bd57557217e8613701506a9e3f0/.github/workflows/base.yml#L102-L158
