### ISSUE TITLE
Cleanup fails for windows, and marks the entire workflow as failed

### ISSUE THREAD

**Issue by divs1210** [graalvm/setup-graalvm#24]
<img width="960" alt="Screenshot 2022-11-25 at 3 37 43 PM" src="https://user-images.githubusercontent.com/3773773/203957636-4ebac494-cf30-4a78-84c9-f5a1c7c261f9.png">

**Comment by fniephaus** [comment]
Thanks for the bug report! Could you please provide a link to the failing build?
It seems that the build output JSON is malformed, which we need to fix. Also, the build report infrastructure should not fail the build. We'll look into fixing both next week. In the meantime, please disable build reports on Windows.

**Comment by divs1210** [comment]
Thanks!

[Link to failing build](https://github.com/divs1210/simple-stackless-lisp/actions/runs/3547020027/jobs/5956683453).

**Comment by fniephaus** [comment]
Thanks for the link. It seems that you're setting "-H:Name" to a path, which I think may cause the problem. I'll do some more investigation next week.

**Comment by fniephaus** [comment]
The builds should no longer be marked as failed if report generation fails. Also, we're looking into fixing the malformed JSON issue in the next GraalVM release.

**Comment by fniephaus** [comment]
The fix for Native Image landed with: https://github.com/oracle/graal/pull/5634.
