### ISSUE TITLE
add to marketplace

### ISSUE THREAD

**Issue by cforce** [graalvm/setup-graalvm#27]
I would like to use in in my github enterprise setup. Currently its not on marketplace, is it?

**Comment by fniephaus** [comment]
`setup-graalvm` is on the GitHub Marketplace (see [here](https://github.com/marketplace/actions/github-action-for-graalvm)). Is there another marketplace this action needs to be added to?

**Comment by cforce** [comment]
I assume that is the root cause of "not found"

<img width="372" alt="image" src="https://user-images.githubusercontent.com/393286/206466308-b0ff5ca7-69c8-443f-98bd-c58409182b3f.png">

**Comment by cforce** [comment]
Yes, i think it does

**Comment by fniephaus** [comment]
Please try again and let us know if it's working for you now. Thanks!

**Comment by cforce** [comment]
Tx this seems to be fixed now

**Comment by fniephaus** [comment]
Great, thanks for confirming!
