### ISSUE TITLE
Error breaking our CI all the time: `API rate limit exceeded for ...`

### ISSUE THREAD

**Issue by guizmaii** [graalvm/setup-graalvm#28]
Hey there 🙂

We're using this action to setup our JVM in our CI tasks, and we're getting more and more of these errors:
<img width="1310" alt="Screenshot 2022-12-20 at 11 11 48 am" src="https://user-images.githubusercontent.com/1193670/208573241-02c7947f-f19d-4080-9f3d-d7799f354ebe.png">

It's really annoying to have a flaky CI because of these errors 😕

**Comment by fniephaus** [comment]
Hi @guizmaii, are you providing a [`github-token`](https://github.com/graalvm/setup-graalvm/tree/4aba115fa5a252b6991d4acc2003118e93c62e9e#options)? Also, it appears that GitHub Actions is having [an incident](https://www.githubstatus.com/incidents/cb6ljbzhktxd) at the moment.

**Comment by guizmaii** [comment]
Thanks. I've added it everywhere. Let's hope it fixes the issse 🙏
