### ISSUE TITLE
Unable to get `GraalVM dev build for Java 17` normally

### ISSUE THREAD

**Issue by linghengqian** [graalvm/setup-graalvm#30]
- In https://github.com/oracle/graalvm-reachability-metadata/actions/runs/3975259643/jobs/6815005161 and https://github.com/apache/shardingsphere/actions/runs/3975559669/jobs/6815495150 , cannot get `GraalVM dev build for Java 17` as normal. Github Actions pops up the following Log.
```shell
Error: Could not find GraalVM dev build for Java 17. It may no longer be available, so please consider upgrading the Java version. If you think this is a mistake, please file an issue at: https://github.com/graalvm/setup-graalvm/issues.
```
- Link to https://github.com/oracle/graalvm-reachability-metadata/pull/170 and https://github.com/apache/shardingsphere/issues/21347 .
- After I checked https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/23.0.0-dev-20230121_0417, I think `setup-graalvm` should have logic to try to use previous `dev builds of GraalVM CE`, instead of always pointing to the `latest GraalVM CE dev build`, so that when the `dev build of GraalVM CE` only releases `JDK 19` products, `setup-graalvm` users can still use the previous `JDK 17 dev build` products normally.

**Comment by alvarosanchez** [comment]
@fniephaus this could be solved if the following would be supported:

```yaml
- uses: graalvm/setup-graalvm@v1
  with:
    version: 'dev'
    java-version: 'dev'
```

**Comment by fniephaus** [comment]
Thanks for raising this issue, @linghengqian.

> `setup-graalvm` should have logic to try to use previous dev builds of GraalVM CE

That won't solve your issue because GraalVM dev builds are volatile and will be removed at some point. So even if you see an older JDK17 dev build, it will no longer be available after a few days/weeks and then your builds will start failing.

> this could be solved if the following would be supported:

Yes, I think we can support `java-version: dev`, although it may still break your builds if your codebase doesn't support building against the latest Java version.

**Comment by fniephaus** [comment]
Please take a look at #31, @linghengqian and @alvarosanchez.

**Comment by linghengqian** [comment]
> Please take a look at #31, @linghengqian and @alvarosanchez.

LGTM!
