### ISSUE TITLE
aarch64 support on GitHub runners

### ISSUE THREAD

**Issue by axelfontaine** [graalvm/setup-graalvm#33]
While this is available on self-hosted runners, it is quite cumbersome to setup.

A nice stop-gap alternative until GitHub provides aarch64 runners could be to have the action use qemu to transparently build aarch64 images on x64.

**Comment by fniephaus** [comment]
Thanks for raising this. You should be able to un on emulated aarch64 on GitHub Actions using something like [uraimo/run-on-arch-action](https://github.com/uraimo/run-on-arch-action). Note, however, this is significantly slower and prone to emulation errors. The proper way to avoid this is indeed if GitHub provides aarch64 runner, so I suggest you comment on and subscribe to https://github.com/actions/runner-images/issues/5631.

Alternatively, I suggest you check out this blog post: [Use Oracle Cloud Infrastructure compute instances as custom GitHub runners](https://info.michael-simons.eu/2022/10/15/use-oracle-cloud-infrastructure-compute-instances-as-custom-github-runners/).

For said reasons, we unfortunately cannot support emulated aarch64 in this action.
