### ISSUE TITLE
Create new tags to version by hash

### ISSUE THREAD

**Issue by ben-manes** [graalvm/setup-graalvm#39]
I noticed that you are modifying the v1 tag to a new hash instead of creating a new version. I observed this when investigating why dependabot tried to upgrade the action and [failed](https://github.com/ben-manes/caffeine/pull/939), as it seems github is confused as to which hash to use, accidentally taking the initial commit.

A github action will automatically take the latest minor version, e.g. `v1` is treated as a dynamic version of 1.+. The repository can publish `v1.1` and `v1.2.3`, but will not upgrade to the next major version, e.g. `v2`.

Modifying the tag is a potential security vulnerability as it may run unverified code on the consumer repository. By using the sha1 hash the action is tied to a specific version and dependabot can still recommend updates. [OpenSSF Scorecard](https://securityscorecards.dev/) will detect non-sha1 usages and and Apache [disallows](https://infra.apache.org/github-actions-policy.html) it for their repositories.

Please switch to immutable tags so that the community can (a) automatically upgrade our hashes and (b) safeguard from supply chain attacks.

**Comment by fniephaus** [comment]
Hi @ben-manes,

Thanks for raising this.

> A github action will automatically take the latest minor version, e.g. v1 is treated as a dynamic version of 1.+.

Are you sure this is really the case? `setup-java`, for example, also has a mutable [`v3` tag](https://github.com/actions/setup-java/releases/tag/v3). If you could help find some official docs or statements on this, that'd be great.

I guess what we could do is use `v1` branch to resolve `graalvm/setup-graalvm@v1` instead of a tag. But before coming up with some custom solution, we should just follow some best practice on this.

**Comment by fniephaus** [comment]
I just found the official [versioning docs](https://github.com/actions/toolkit/blob/74906bea83a0dbf6aaba2d00b732deb0c3aefd2d/docs/action-versioning.md) from GitHub and I guess we're doing exactly what is recommended (version tags and major version tag). Have you raised your concern with the GitHub team already?

**Comment by ben-manes** [comment]
Oh! I’m sorry, I misunderstood how it worked then from how it is described to end users. What about releasing the minor versions so that hash versioning will update automatically? I guess since you only reset the major it wasn’t picking that up properly. What I wanted was something like [this](https://github.com/ben-manes/caffeine/commit/f12dac2665e4d94c42c31905746b2f209d9d4b05).

**Comment by fniephaus** [comment]
We do have lots of [version tags](https://github.com/graalvm/setup-graalvm/tags) and you should be able to lock the version using something like `graalvm/setup-graalvm@v1.0.11`. We just don't make GitHub releases for them. Is there a point in making such releases other than being able to add a changelog?

**Comment by fniephaus** [comment]
>A release has a flag if it is the latest so it might query for that rather than infer it from tags.

Right, I'm not aware anyone is querying for the latest version via the GitHub release API. If that's a use case, let us know.

Again, thanks for raising this anyway!
