### ISSUE TITLE
Error since latest release of GraalVM

### ISSUE THREAD

**Issue by benweet** [graalvm/setup-graalvm#42]
Since the latest release of GraalVM one hour ago (https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-20.0.1) we're having this error :

<img width="930" alt="Screenshot 2023-06-13 at 17 04 35" src="https://github.com/graalvm/setup-graalvm/assets/1005257/75b23f1f-203e-4ae1-8abb-99982dfbade8">

It seems the release name prefix is `jdk-` whereas it's supposed to be `vm-` :
https://github.com/graalvm/setup-graalvm/blob/babc303d7e5b8f3062a94b90b49c3444cf291633/src/graalvm.ts#LL28C28-L28C46

**Comment by fniephaus** [comment]
I have just deployed a temporary fix to unblock all `latest` builds while we are still rolling out the new release: https://github.com/graalvm/setup-graalvm/commit/b11d36630f94ed5864e0a680a979b5afde449e9d

**Comment by benweet** [comment]
Thanks @fniephaus 👍 

I can confirm it's working now :

<img width="1192" alt="Screenshot 2023-06-13 at 18 37 58" src="https://github.com/graalvm/setup-graalvm/assets/1005257/44b2c121-026c-4aed-aa75-b8fd2408b71d">

**Comment by fniephaus** [comment]
Hold on, let's make sure we clean this up and not break anything. Nothing is usually more permanent than a temporary fix, but this one is not allowed to stay very long. :wink:

**Comment by ArloL** [comment]
I am using fixed versions of the setup-graalvm action like this: `uses: graalvm/setup-graalvm@v1.0.11`. Just to be clear: the fix requires an update of the action to have functioning builds again, right?

If yes: Is there no other way to restore `1.0.11`'s functionality - I am half asking out of laziness and the other half out of stability/reproducability reasons.
If an update is necessary: would you please release a new tag, so that the update can be performed via dependabot? Again being lazy :)

**Comment by fniephaus** [comment]
>the fix requires an update of the action to have functioning builds again, right?

Yes, that is correct.

>Is there no other way to restore 1.0.11's functionality - I am half asking out of laziness and the other half out of stability/reproducability reasons.

We could move the tag but that is also not a viable solution because a) all tags are stable except for the major tag (`v1`) and b) we'd need to do this for all tags.

> If an update is necessary: would you please release a new tag, so that the update can be performed via dependabot? Again being lazy :)

Of course, [v1.0.12](https://github.com/graalvm/setup-graalvm/releases/tag/v1.0.12) is up now. :)

**Comment by fniephaus** [comment]
Cleaned up now in https://github.com/graalvm/setup-graalvm/commit/6a5fa2da729df36f5a1cdb0c6e777d1da45729ec and https://github.com/graalvm/setup-graalvm/commit/9180004c5f95421dcd72a5681d0b46ee46df4b6e.
