### ISSUE TITLE
Update instructions for the latest GraalVM version

### ISSUE THREAD

**Issue by axelfontaine** [graalvm/setup-graalvm#44]
Now that the versioning scheme changed (see https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-20.0.1), the instructions should be updated to show how to use the new 20.x and 17.x versions.

**Comment by fniephaus** [comment]
Thanks for raising this, @axelfontaine. We are already working on updates for this action, more info will follow shortly as part of #45.
