### ISSUE TITLE
Ensure specific release instead of 21.latest

### ISSUE THREAD

**Issue by borkdude** [graalvm/setup-graalvm#63]
I'd like to download specific releases of Oracle GraalVM 21, like 21.0.0 and not get the 21 latest automatically.

As discussed on Slack with @fniephaus:

> good question, I don’t think you can at the moment. the logic is [here](https://github.com/graalvm/setup-graalvm/blob/6c7d417a1ef253f4d667a69e6a5716927746e251/src/graalvm.ts#L31) and does not take into GA releases account. Can you file a ticket so we can look into it?

**Comment by fniephaus** [comment]
The [script-friendly URL](https://www.oracle.com/java/technologies/jdk-script-friendly-urls/) are unfortunately a bit awkward with the regard to GA vs latest releases:

- https://download.oracle.com/java/<major version>**latest**/jdk-<major version>_linux-x64_bin.tar.gz links to the latest version
- https://download.oracle.com/java/<major version>**archive**/jdk-<major version>_linux-x64_bin.tar.gz links to the GA version

I'm proposing to work around this by putting the following special handling for GA versions in place:

- `java-version: '21'` will continue to use `latest` for the latest version
- `java-version: 21.0.0` will use `archive` for the GA version

Does this makes sense to you?

**Comment by borkdude** [comment]
Sounds like a good solution to me!
