### ISSUE TITLE
Upgrade Node to v20

### ISSUE THREAD

**Issue by fniephaus** [graalvm/setup-graalvm#72]
We should probably upgrade Node to v20 at some point. `setup-java` has already done this: https://github.com/actions/setup-java/pull/558

**Comment by marcphilipp** [comment]
I'm now getting deprecation warnings from GitHub Actions:
https://github.com/junit-team/junit5/actions/runs/7697372946?pr=3665

**Comment by fniephaus** [comment]
Thanks for the ping, @marcphilipp. We'll look into this shortly!
