### ISSUE TITLE
Native build error on windows and macOS suddenly

### ISSUE THREAD

**Issue by GrapeBaBa** [graalvm/setup-graalvm#74]
I  can't reopen the issue, removed the version still not works.

https://github.com/optimism-java/hildr/actions/runs/7231369944/workflow

**Comment by fniephaus** [comment]
It seems you are building with Gradle and caching is enabled, which you may want to clear. I'm not sure Gradle actually runs on JDK 21 already. Could you try running it on JDK 17 and then set `GRAALVM_HOME` to a GraalVM for JDK 21? [Here's an example](https://github.com/oracle/graalvm-reachability-metadata/blob/8d60c36e5890409c0f7feb8054c8df16d6eea848/.github/workflows/test-changed-metadata.yml#L53-L65) how that can be done: add `set-java-home: 'false'` to ensure the action does not overwrite a previously set `JAVA_HOME`.

**Comment by GrapeBaBa** [comment]
@fniephaus I can't get you, I use this template only adding cache https://github.com/graalvm/setup-graalvm?tab=readme-ov-file#quickstart-template.

**Comment by GrapeBaBa** [comment]
> @fniephaus I can't get you, I use this template only adding cache https://github.com/graalvm/setup-graalvm?tab=readme-ov-file#quickstart-template.

Also after I change `./gradlew nativeCompile` to `native-image`, it works fine. It should be an issue about graalvm gradle plugin.

**Comment by fniephaus** [comment]
Ok good! Feel free to file a ticket against the Native Build Tools at https://github.com/graalvm/native-build-tools/issues
