### ISSUE TITLE
Issues downloading GVM 21

### ISSUE THREAD

**Issue by sgammon** [graalvm/setup-graalvm#75]
We started seeing this in our pipelines today:

<img width="726" alt="Screenshot 2023-12-18 at 1 40 16 PM" src="https://github.com/graalvm/setup-graalvm/assets/171897/b52cf7e2-8bef-4ec0-8c93-6a234c42b7e6">

Not sure what's going wrong or what changed? We haven't upgraded the action lately

**Comment by fniephaus** [comment]
Do you have a link to such a failing build?

**Comment by fniephaus** [comment]
Is this still an issue?

**Comment by sgammon** [comment]
@fniephaus This is not still an issue 😄 Thank you for your quick response.
