### ISSUE TITLE
suddenly fails with Java 8

### ISSUE THREAD

**Issue by esaulpaugh** [graalvm/setup-graalvm#86]
Probably because --version is not supported on Java 8. It should be -version

Successfully set up 'graalvm-ce-java8-21.2.0'
  /opt/hostedtoolcache/graalvm-ce-java8-linux/21.2.0/x64/graalvm-ce-java8-21.2.0/bin/java --version
  Unrecognized option: --version
  Error: Could not create the Java Virtual Machine.
  Error: A fatal exception has occurred. Program will exit.
  Error: The process '/opt/hostedtoolcache/graalvm-ce-java8-linux/21.2.0/x64/graalvm-ce-java8-21.2.0/bin/java' failed with exit code 1

**Comment by fniephaus** [comment]
Thanks for the report, @esaulpaugh. We'll get this fixed asap.

**Comment by fniephaus** [comment]
This should be fixed now. Please restart your builds :)
