### ISSUE TITLE
do you publish release notes for the releases?

### ISSUE THREAD

**Issue by sdelamo** [graalvm/setup-graalvm#93]
I wanted to check if 1.2.1 was safe to upgrade to. But I did not find any release notes. 
https://github.com/graalvm/setup-graalvm/releases

**Comment by fniephaus** [comment]
Hey @sdelamo,
thanks for the suggestion!

We should've done this earlier but now that this action is used by a lot more projects, we certainly need to do it. I've created releases for `v1.0.0`, `v1.1.0`, `v1.2.0`, and the latest `v1.2.1`, and we'll add new ones for every new version that is released from now on.

Hope this helps!
