### ISSUE TITLE
Updating  GraalVM to 23-ea doesn't pull the necessary EA version 

### ISSUE THREAD

**Issue by olyagpl** [graalvm/setup-graalvm#97]
The job https://github.com/olyagpl/langchain4j-searchbot/actions/runs/9479855945/job/26119305292?pr=2 pulled Oracle GraalVM 23-dev+23.1 instead of JDK 23 EA BUILD 13 introduced in https://github.com/graalvm/oracle-graalvm-ea-builds/commit/42ac13ece6ced5072ab199f7007e97ff8f8e1abd.

**Comment by fniephaus** [comment]
EA build 13 is `23-dev+23.1` so you did get the right version. I know it's a bit confusing, hopefully we can clean this up soon.
